#!/usr/bin/RScript

library(wgsea)
##EXPECTS
## comma separated list of w.param files (as generated by VSEAMS::Runnable::CalcWilcoxonParams)
##w_param_files<-'file1.RData,file2.RData'
##out_file

args<-commandArgs(TRUE)
if(length(args) < 2){
  cat("Error incorrect number of args","\n",sep="")
  q()
}else{
  for(i in 1:length(args)){
    eval(parse(text=args[[i]]))
  }
}

wfname<-unlist(strsplit(w_param_files,","))
wl<-lapply(wfname,function(x) get(load(x)))
Wstar<-lapply(wl,function(x) x$wstar)
W<-lapply(wl,function(x) x$w)
n.in<-sapply(wl,function(x) x$n.in)
n.out<-sapply(wl,function(x) x$n.out)
enrich<-Z.value(W=W,Wstar=Wstar,n.in=n.in,n.out=n.out)
save(enrich,file=out_file)
print("Success")
